SELECT LINK_NO, CIS_MARKER, ADMISSION_DATE, DISCHARGE_DATE,
  ADMISSION_TYPE, DISCHARGE_TYPE, DR_POSTCODE as postcode
  FROM ANALYSIS.SMR01_PI
  WHERE ((ANALYSIS.SMR01_PI.RECORD_TYPE = '01B')
  AND (DISCHARGE_DATE >= '01-APR-2013')
  AND (AGE_IN_YEARS >= 18)
  AND LINK_NO is not NULL)
