SELECT DISCHARGE_DATE, DR_POSTCODE as postcode,
  MAIN_CONDITION, OTHER_CONDITION_1, OTHER_CONDITION_2,
  OTHER_CONDITION_3, OTHER_CONDITION_4, OTHER_CONDITION_5
  FROM ANALYSIS.SMR01_PI
  WHERE ((DISCHARGE_DATE >= '{min_date}')
  AND (AGE_IN_YEARS >= 65)
  AND (INPATIENT_DAYCASE_IDENTIFIER = 'I')
  AND (ADMISSION_TYPE Between 33 AND 35)
  AND (SEX In ('1', '2'))
  AND (DR_Postcode is not NULL))
  Order By DR_Postcode
